# -*- coding: utf-8 -*-
"""파이썬0326.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dwQpnA8SAenjcjsTLG9poKxrL92G2lgC
"""

fruit = ['사과','딸기','체리']
name = input("과일을 입력하세요!")
if name in fruit:
  print("집에 있음.")
else:
  print("{} 를 구입하세요.".format(name))

fruit = {'봄':'딸기','여름':'토마토','가을':'사과'}
a = input("내가 좋아하는 계절은?")
if a in fruit:
  print('정답입니다')
else:
  print('오답입니다')

fruit = {'봄':'딸기','여름':'토마토','가을':'사과'}
a = input("내가 좋아하는 과일은?")
if a in fruit.values():
  print('정답입니다')
else:
  print('오답입니다')

sa = input('번호를 입력하세요')
num = sa.split('-')[0]
if num == '011':
  ab == 'skt'
elif num == '016':
  ab == 'kt'
elif num == '019':
  ab == 'lgu'
else:
  ab =='알수없는'
print('당신은 {} 사용자입니다.'.format(ab))