# -*- coding: utf-8 -*-
"""파이썬0316.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NsN-XoB2RRfaRxVTHDOeJtXiiKJWfvjB
"""

#dictionary

big_data = {3:'세명', 100:'컴퓨터'}
print(big_data)
print(big_data[3])
print(big_data[100])

print(big_data.get(1,'인공'))
print(big_data)

small_data = {'a-1':'세명','a-2':'홍길동'}
print(small_data)

print(small_data.keys())
print(small_data.values())
print(small_data.items())

menu={'커피','우유','주스'}
print(menu,type(menu))

menu = list(menu)
print(menu,type(menu))

from random import *
id_list = [1,2,3,4,5]
print(id_list)

shuffle(id_list)
print(id_list)

print(sample(id_list,2))

from random import *
# id_list = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
id_list = range(1,21)
dang= sample(id_list,4)

print("치킨 당첨자는 "+ str(dang[:1])+" 번 입니다!" )
print("커피 당첨자는 "+ str(dang[1:4])+ " 번 입니다!")
print("축하드립니다!")

# if 문

weather = '미세먼지'

if weather == '비':
  print('우산을 챙기세요')
elif weather == '미세먼지':
  print('마스크를 챙기세요')
else:
  print('준비물 필요 없음')

weather = input('오늘 날씨 어때요? :' )

if weather == '비':
  print('우산을 챙기세요')
elif weather == '미세먼지':
  print('마스크를 챙기세요')
else:
  print('준비물 필요 없음')

temp = input('오늘 기온은 몇도에요? :' )

if float(temp) >= 30:
  print('너무 더워요')
elif float(temp) >= 10:
  print('괜찮은 날씨에요')
else:
  print('추워요')

for waiting_no in [0,1,2,3,4]:
  print('대기번호: {} '.format(waiting_no))

  if waiting_no == 3:
    break

for waiting_no in range(0,5):
  print('대기번호: {} '.format(waiting_no))

st = ['aaa','bbb','ccc']
for waiting_no in st:
  print('대기번호: {} '.format(waiting_no))