# -*- coding: utf-8 -*-
"""파이썬0323.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vw-XXmcQ4jCY-BEuWyHwDGNC8YAn_OqE
"""

def open_account():
  print('새로운 계좌 생성')

def deposit(balance, money):
  print('입금 완료') 
  return balance+money

def withdraw(balance, money):
  if balance > money:
    print('출금 완료')
    return balance - money
  else:
    print('출금불가')
    return balance

def withdraw_night(balance,money):
  commission = 200
  return commission, balance - money - commission

balance = 0
balance = deposit(balance, 1000)
print('현재 잔액 : ',balance)

balance = deposit(balance, 1000)
print('현재 잔액 : ',balance)

commission,balance = withdraw_night(balance,1000)
print('수수료: {}, 잔액: {}'.format(commission,balance))