# -*- coding: utf-8 -*-
"""파이썬0319.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_W15kGVnhAjp0XTUym2EET1FpRNQd_qx
"""

students = ['아이언맨','토르','그루트']
students = [len(i) for i in students]
print(students)

from random import *
cnt = 0
for i in range(1,51):
  time = randrange(5,51)
  if 5 <= time <= 15:
    print('[O] {0}번쨰 손님 (소요시간 : {1}분)'.format(i,time))
    cnt += 1
  else :
    print('[ ] {0}번쨰 손님 (소요시간 : {1}분)'.format(i,time))
print('총 탑승 승객 : {}분'.format(cnt))