# -*- coding: utf-8 -*-
"""0401.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JEOLZI8wk8YR4oawqYNbX3fCW079X_Ob
"""

cof = 300
n=5

while n >= 0:
    
    
    if n == 0:
      print('커피가 떨어졌습니다.')
      break

    don = int(input('돈을 넣어주세요'))
    b = don - cof

    if b > 0:
      print('거스름돈 {} 을 주고 커피를 줍니다\n'.format(b))
      n = n-1

    elif b == 0:
      print('커피를 줍니다\n'.format(b))
      n = n-1

    else:65
      print('돈을 다시 돌려주고 커피를 주지 않습니다.')
      print('남은 커피의 양은 {}개 입니다.\n'.format(n))

list_a = [ j for j in range(10) ]
print(list_a)

y = []
for i in list(range(2, 20 ,2)):
    y.append(i)
print(y)

list_b = [ j * 2 for j in range(10) ]
print(list_b)

a = [1,2,3,4,5,6,7,8,9]

result = []
for i in a:
  if i%2 == 0:
    result.append(i*2)
print(result)

a = [1,2,3,4,5,6,7,8,9]
result = [ i*2 for i in a if i%2==0 ]
print(result)

a = [1,2,3,4,5,6,7,8,9]

result = []
for i in a:

  if i%2 == 0:
    result.append(i*2)

  else:
    result.append(-1)

print(result)

a = [1,2,3,4,5,6,7,8,9]
result = [ i*2 if (i%2==0) else -1 for i in a]
print(result)