# -*- coding: utf-8 -*-
"""파이썬0402.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11EPBEa9q-A31JAEdK_WYBUWuRnUg6R_o
"""

def score(score_list):
  print(sum(score_list)/len(seore_list))
  
score([99,23,54,75,23,3,4,45,78,96,47,99])

a = [3,100,66,44]
result = [i for i in a if (i%3==0)]

print(result)