# -*- coding: utf-8 -*-
"""파이썬0312.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--swNECLYlW2JrkkFtUCj7HXhGET1wx9
"""

subway = ['세명','컴퓨터','고등학교']
print(subway)
print(type(subway)) 
print(subway.index('컴퓨터'))

subway.append('소프트웨어과')

print(subway)

subway.insert(2,'인공지능')
print(subway)


print(subway.pop())
print(subway)

print(subway.pop())
print(subway)

subway.append('세명')
print(subway.count('세명'))

subway.reverse()
print(subway)