# -*- coding: utf-8 -*-
"""파이썬0318.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJUDe-azx40h-NHz_p1nb_vxyXC5QoeT
"""

#while

customer = '길동이'
index = 5

while index >= 1:
  print('{0}. 커피가 준비 되었습니다. {1} 번 남았어요'.format(customer , index))
  index -=1
  if index == 0:
    print('커피가 폐기 처분 되었네요')

person = '몰라요'

while person != customer:
  print('{}, 커피가 준비 되었습니다.'.format(customer))
  customer = input('이름이?')

absent = [2,5]
no_book = [7]

for student in range(1,11):
  if student in absent:
    continue
  elif student in no_book:
    print('오늘 수업 여기까지, {}는 교무실로'.format(student))
    break
  print('{}, 조용히 자습해라'.format(student))

student = [1,2,3,4]

# for student in range(1,5):
#   student += 100
#   print(student)

students = [ i + 100 for i in student]
print(students)