# -*- coding: utf-8 -*-
"""파이썬0330.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WLbKAMorucIiMd_SqqOfMpDy6Dh5dzpb
"""

brand = {'011':'skt', '016':'kt','019':'lgu','010':'알수없음'}
aaa = input('번호를 입력하세요')
num = aaa.split('-')[0]

if brand.get(num):
  print(brand.get(num))
else:
  print('몰라요')

a = input('번호를 입력하세요')
num = a[:3]
if num in ['010' , '011' , '012']:
  print('은평구')
elif num in ['013' , '014']:
  print('중구') 
elif num in ['015' , '016']:
  print('서대문구') 
elif num in ['017' , '018']:
  print('마포구') 
else:
  print('용산구')

b = ['sk하닉','삼성','lg']

for i in b:
  print(len(i))

for i in range(0,len(b)):
  print(len(b[i]))

print(len(b[0]))
print(len(b[1]))
print(len(b[2]))

a = 11
for i in range(a+1):
  print(a)
  a=a-1

low = [100,200,400,800,1000]
high = [150,300,430,880,1000]

v = []

for i in range(0,len(low)):
  v.append(high[i] - low[i])

print(v)

i = 1
while (i<4):
  print('{}번 학생'.format(i))
  i += 1
print('end')

i = 1
sum = 0
while (i<101):
  sum += i
  i+=1
print('합은 {} 입니다'.format(sum))